if: tag IS blank
branches:
  only:
    - master
    - develop

sudo: required
services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker

before_install:
  - | # Load cached docker images.
    if [[ -d $HOME/docker ]]; then
      ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load";
    fi

before_script:
  - ./develop build
  - ./develop up -d
  - ./develop composer install
  - ./develop run --rm -T -w /var/www/html api mv .env.ci .env
  - ./develop artisan key:generate
  - ./develop artisan passport:keys

script:
  - ./develop phpunit

before_cache:
  - > # Save tagged docker images.
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

after_failure:
  - cat storage/logs/testing.log

before_deploy:
  - ./docker/build

deploy:
  - provider: script
    script: SERVICE=$API_SERVICE ./docker/deploy
    on:
      branch: develop
  - provider: script
    script: SERVICE=$QUEUE_WORKER_SERVICE ./docker/deploy
    on:
      branch: develop
  - provider: script
    script: SERVICE=$SHCEDULER_SERVICE ./docker/deploy
    on:
      branch: develop
