if: tag IS blank
branches:
  only:
    - master
    - develop

sudo: required
services:
  - docker

before_script:
  - ./develop build
  - ./develop up -d
  - ./develop composer install

script:
  - ./develop phpunit
