version: "3"

services:
  api:
    image: BookATest.hiv/api
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-net

  queue-worker:
    image: BookATest.hiv/api
    volumes:
      - .:/var/www/html
    networks:
      - app-net
    working_dir: /var/www/html
    command: php artisan queue:work --tries=1

  scheduler:
    image: BookATest.hiv/api
    volumes:
      - .:/var/www/html
    networks:
      - app-net
    working_dir: /var/www/html
    command: php artisan schedule:loop

  node:
    image: BookATest.hiv/node
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-net

  redis:
    image: redis:5.0-alpine
    volumes:
      - redis-data:/data
    networks:
      - app-net

  troposphere:
    image: BookATest.hiv/troposphere
    build:
      context: ./docker/troposphere
      dockerfile: Dockerfile
    volumes:
      - ./aws:/tmp
    command: "python ${CF_TEMPLATE}"

networks:
  app-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local

  redis-data:
    driver: local
