version: "3"

services:
  api:
    image: bookatest/api
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-net

  queue-worker:
    image: bookatest/api
    volumes:
      - .:/var/www/html
    networks:
      - app-net
    command: php artisan queue:work --tries=1

  scheduler:
    image: bookatest/api
    volumes:
      - .:/var/www/html
    networks:
      - app-net
    command: php artisan schedule:loop

  node:
    image: bookatest/node
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html

  mysql-testing:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    networks:
      - app-net

  redis-testing:
    image: grokzen/redis-cluster:5.0.2
    environment:
      REDIS_CLUSTER_IP: 0.0.0.0
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
