openapi: "3.0.1"

info:
  title: "HIV API Specification"
  description: "For using the HIV API"
  version: "v1"
  contact:
    name: "Ayup Digital"
    url: "https://ayup.agency"

servers:
- url: "https://api.hiv.test/v1/"
  description: "Dev Server"

paths:
  /users:
    post:
      tags:
        - "Users"
      summary: "Create a new user"
      operationId: "users.store"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ModifyUser"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    get:
      tags:
        - "Users"
      summary: "List all users"
      operationId: "users.list"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserCollection"
  /users/{id}:
    get:
      tags:
        - "Users"
      summary: "Get a specific user"
      operationId: "users.show"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    put:
      tags:
        - "Users"
      summary: "Update a specific user"
      operationId: "users.update"
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ModifyUser"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    delete:
      tags:
        - "Users"
      summart: "Delete a specific user"
      operationId: "users.destroy"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeletedResponse"
  /locations:
    post:
      tags:
        - "Locations"
      summary: "Create a new location"
      operationId: "locations.store"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ModifyLocation"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
    get:
      tags:
        - "Locations"
      summary: "List all locations"
      operationId: "locations.list"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LocationCollection"
  /locations/{id}:
    get:
      tags:
        - "Locations"
      summary: "Get a specific location"
      operationId: "locations.show"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
    put:
      tags:
        - "Locations"
      summary: "Update a specific location"
      operationId: "locations.update"
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ModifyLocation"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
    delete:
      tags:
        - "Locations"
      summart: "Delete a specific location"
      operationId: "locations.destroy"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeletedResponse"
  /locations/{id}/appointments:
    post:
      tags:
        - "Appointments"
      summary: "Create a new appointment"
      operationId: "appointments.store"
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ModifyAppointment"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Appointment"
    get:
      tags:
        - "Appointments"
      summary: "List all appointments"
      operationId: "appointments.list"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppointmentCollection"
  /appointments/{id}:
    get:
      tags:
        - "Appointments"
      summary: "Get a specific appointment"
      operationId: "appointments.show"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Appointment"
    put:
      tags:
        - "Appointments"
      summary: "Update a specific appointment"
      operationId: "appointments.update"
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ModifyAppointment"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Appointment"
    delete:
      tags:
        - "Appointments"
      summart: "Delete a specific appointment"
      operationId: "appointments.destroy"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeletedResponse"

components:
  securitySchemes:
    app_id:
      type: "apiKey"
      description: "API key to authorize requests"
      name: "appid"
      in: "query"
  parameters:
    id:
      name: "id"
      in: "path"
      description: "The ID of the model"
      schema:
        type: "integer"
  schemas:
    DeletedResponse:
      type: "object"
      properties:
        message:
          type: "string"
          example: "Model successfully deleted"
    ApiResourceMeta:
      type: "object"
      properties:
        current_page:
          type: "integer"
        from:
          type: "integer"
        last_page:
          type: "integer"
        path:
          type: "string"
          example: "http://example.com/pagination"
        per_page:
          type: "integer"
        to:
          type: "integer"
        total:
          type: "integer"
    ApiResourceLinks:
      type: "object"
      properties:
        first:
          type: "string"
          example: "http://example.com/pagination?page=1"
        last:
          type: "string"
          example: "http://example.com/pagination?page=1"
        prev:
          type: "string"
          nullable: true
        next:
          type: "string"
          nullable: true
    ModifyUser:
      type: "object"
      required:
        - "name"
        - "email"
        - "password"
      properties:
        location_id:
          type: "integer"
        name:
          type: "string"
        email:
          type: "string"
          format: "email"
        password:
          type: "string"
          format: "password"
    User:
      type: "object"
      properties:
        id:
          type: "integer"
        location_id:
          type: "integer"
          nullable: true
        profile_picture_file_id:
          type: "integer"
          nullable: true
        name:
          type: "string"
        email:
          type: "string"
          format: "email"
        password:
          type: "string"
          format: "password"
    UserCollection:
      type: "object"
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/User"
        links:
          $ref: "#/components/schemas/ApiResourceLinks"
        meta:
          $ref: "#/components/schemas/ApiResourceMeta"
    ModifyLocation:
      type: "object"
      required:
        - "name"
      properties:
        name:
          type: "string"
    Location:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
    LocationCollection:
      type: "object"
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/Location"
        links:
          $ref: "#/components/schemas/ApiResourceLinks"
        meta:
          $ref: "#/components/schemas/ApiResourceMeta"
    ModifyAppointment:
      type: "object"
      required:
        - "start_at"
      properties:
        start_at:
          type: "string"
          example: "YYYY-MM-DD H:i:s"
    Appointment:
      type: "object"
      properties:
        id:
          type: "integer"
        start_at:
          type: "string"
          example: "YYYY-MM-DD H:i:s"
    AppointmentCollection:
      type: "object"
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/Appointment"
        links:
          $ref: "#/components/schemas/ApiResourceLinks"
        meta:
          $ref: "#/components/schemas/ApiResourceMeta"

security:
  - app_id: []

tags:
  - name: "Users"
    description: "Backend users"
  - name: "Locations"
    description: "Clinic locations"
  - name: "Appointments"
    description: "Appointments at locations"

externalDocs:
  description: "External Doc Website"
  url: "https://ayup.agency"
